### ISSUE TITLE
Error when installed in Windows XP

### ISSUE THREAD

**Issue by GoogleCodeExporter** [niazalikhan87/qutip#14]
```
hello,

when I install QuTip-1.1.3-4 in my computer,
system environment:Windows XP
IDLE version:2.7.3
Install steps:unzip the source file->copy this file to the 
\Python\Lib\site-packages\QuTiP directory->run the setup.py file in IDLE

some errors reported as follows:



Warning (from warnings module):
  File "D:\Python2\lib\distutils\dist.py", line 267
    warnings.warn(msg)
UserWarning: Unknown distribution option: 'include_package_data'

Warning (from warnings module):
  File "D:\Python2\lib\distutils\dist.py", line 267
    warnings.warn(msg)
UserWarning: Unknown distribution option: 'depends'

Traceback (most recent call last):
  File "D:\Python2\Lib\site-packages\QuTiP\setup.py", line 107, in <module>
    include_package_data=True
  File "D:\Python2\lib\distutils\core.py", line 140, in setup
    raise SystemExit, gen_usage(dist.script_name) + "\nerror: %s" % msg
SystemExit: usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] 
...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied


who can do me a favor and give some advices or solution methods, thanks very 
muck!

Christwell.Zhang


```

Original issue reported on code.google.com by `Christwe...@gmail.com` on 20 May 2012 at 11:01

**Comment by GoogleCodeExporter** [comment]
```
The two warnings are not important. From the line "SystemExit: usage: setup.py 
..." is seems like you didn't run the setup.py script with correct arguments 
(you probably left out the 'install' argument). Try to run

python setup.py install

There are detailed installation instructions in the QuTiP documentation at

http://qutip.googlecode.com/svn/doc/1.1.3/html/installation.html
```

Original comment by `jrjohans...@gmail.com` on 21 May 2012 at 12:30

**Comment by GoogleCodeExporter** [comment]
Original comment by `nonhermitian` on 21 May 2012 at 2:11
- Changed state: **Invalid**
