### ISSUE TITLE
qutip.demos() does not work with python 3

### ISSUE THREAD

**Issue by GoogleCodeExporter** [niazalikhan87/qutip#20]
```
What steps will reproduce the problem?
1. Install qutip with python3.2
2. python3 -c "import qutip; qutip.demos()"

What is the expected output? What do you see instead?
Expected: demos

Received:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/gawron/.local/lib/python3.2/site-packages/qutip/demos.py", line 39, in demos
    from gui import Examples
ImportError: No module named gui

What version of the product are you using? On what operating system?

$ uname -a; lsb_release -a
Linux lati 3.5.0-18-generic #29-Ubuntu SMP Fri Oct 19 10:26:51 UTC 2012 x86_64 
x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 12.10
Release:        12.10
Codename:       quantal

$ python3 --version
Python 3.2.3

Please provide any additional information below.
In python 2 works as expected.

```

Original issue reported on code.google.com by `p.w.gaw...@gmail.com` on 9 Nov 2012 at 10:56

**Comment by GoogleCodeExporter** [comment]
```
Hi. Thanks for the issue report. I also noticed that the demos do not work with 
python3 in the latest release of qutip. But it has recently been fixed in the 
development repository on github, so if you try that code it should work fine. 
The problem was some incorrect module import statements which should have been 
fixed.
```

Original comment by `jrjohans...@gmail.com` on 13 Nov 2012 at 8:30
- Changed state: **Fixed**
