### ISSUE TITLE
ImportError: No module named matrix

### ISSUE THREAD

**Issue by GoogleCodeExporter** [niazalikhan87/qutip#4]
```
What steps will reproduce the problem?
1. After installing QuTip, in python I did from qutip import *

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "qutip/__init__.py", line 85, in <module>
    from correlation import *
  File "qutip/correlation.py", line 23, in <module>
    from odesolve import *
  File "qutip/odesolve.py", line 28, in <module>
    from cyQ.matrix import spmv
  File "qutip/cyQ/__init__.py", line 1, in <module>
    from matrix import *
ImportError: No module named matrix



What version of the product are you using? On what operating system?

Lion 10.7.1
Using the Scipy Super pack (latest)


How can I fix this? Thank you very much !!


```

Original issue reported on code.google.com by `than...@gmail.com` on 6 Oct 2011 at 11:10

**Comment by GoogleCodeExporter** [comment]
```
Hi

This problem occurs when you start python or ipython from the qutip directory 
after installing the package (if you do, the files in the CWD is used instead 
of the installed files). To solve this just start python from somewhere else, 
so that the installed library files are used instead.


```

Original comment by `jrjohans...@gmail.com` on 7 Oct 2011 at 2:17

**Comment by GoogleCodeExporter** [comment]
Original comment by `nonhermitian` on 7 Oct 2011 at 2:26
- Changed state: **Done**
